"""Builds continents.js (SVG paths for the 7 continents) from Natural Earth data.

Usage (needs geopandas + shapely + pyproj):
    curl -L -o ne110.geojson https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson
    python build_map.py ne110.geojson
"""
import json
import sys
from pathlib import Path

import geopandas as gpd
from shapely.geometry import box
from shapely.ops import polylabel, unary_union

WIDTH = 1000  # SVG viewBox width; height follows the projection's aspect ratio

CONTINENT_MAP = {
    "Africa": "africa",
    "Asia": "asia",
    "Europe": "europe",
    "North America": "north-america",
    "South America": "south-america",
    "Oceania": "australia",
    "Antarctica": "antarctica",
}

# Natural Earth puts all of Russia in Europe; split it at the Urals (~60E) so Asia looks right.
URALS_LON = 60


def main(src):
    world = gpd.read_file(src)
    pieces = {key: [] for key in CONTINENT_MAP.values()}

    for _, row in world.iterrows():
        cont = row["CONTINENT"]
        geom = row.geometry
        if row["ADM0_A3"] == "RUS":
            # the far-east tip wraps past 180 degrees to negative longitudes, so it stays in Asia
            pieces["europe"].append(geom.intersection(box(0, -90, URALS_LON, 90)))
            pieces["asia"].append(geom.difference(box(0, -90, URALS_LON, 90)))
        elif row["ADM0_A3"] == "FRA":
            # French Guiana is part of France's geometry but belongs on the South America map
            pieces["europe"].append(geom.intersection(box(-30, -90, 180, 90)))
            pieces["south-america"].append(geom.intersection(box(-180, -90, -30, 90)))
        elif cont in CONTINENT_MAP:
            pieces[CONTINENT_MAP[cont]].append(geom)
        # "Seven seas (open ocean)" islands are skipped

    gdf = gpd.GeoDataFrame(
        {"id": list(pieces)},
        geometry=[unary_union(g).buffer(0) for g in pieces.values()],
        crs="EPSG:4326",
    ).to_crs("+proj=robin")

    minx, miny, maxx, maxy = gdf.total_bounds
    scale = WIDTH / (maxx - minx)
    height = round((maxy - miny) * scale)

    def ring_path(coords):
        pts = [((x - minx) * scale, (maxy - y) * scale) for x, y in coords]
        return "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z"

    out, labels = {}, {}
    for _, row in gdf.iterrows():
        geom = row.geometry.simplify(0.35 / scale)
        polys = getattr(geom, "geoms", [geom])
        d = "".join(
            ring_path(p.exterior.coords) + "".join(ring_path(i.coords) for i in p.interiors)
            for p in polys
        )
        out[row["id"]] = d
        biggest = max(polys, key=lambda p: p.area)
        lx, ly = polylabel(biggest, tolerance=1000).coords[0]
        labels[row["id"]] = [round((lx - minx) * scale), round((maxy - ly) * scale)]

    data = {"width": WIDTH, "height": height, "paths": out, "labels": labels}
    target = Path(__file__).with_name("continents.js")
    target.write_text(
        "// Generated by build_map.py from Natural Earth (public domain). Do not edit by hand.\n"
        f"window.CONTINENT_MAP = {json.dumps(data, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"wrote {target} ({target.stat().st_size // 1024} KB), viewBox 0 0 {WIDTH} {height}")


if __name__ == "__main__":
    main(sys.argv[1])
